# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - shawsoft

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with: 
        registry: ghcr.io
        username: ${{ secrets.GHCR_USERNAME }}
        password: ${{ secrets.GHCR_PASSWORD }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          ghcr.io/${{ secrets.GHCR_USERNAME }}/shawsoft-io/run-capture-the-flag:${{ github.sha }}
          ghcr.io/${{ secrets.GHCR_USERNAME }}/shawsoft-io/un-capture-the-flag:latest
        file: ./Dockerfile
        secrets: |
          "auth_secret=${{ secrets.AUTH_SECRET }}"
          "auth_strava_id=${{ secrets.AUTH_STRAVA_ID }}"
          "auth_strava_client_secret=${{ secrets.AUTH_STRAVA_SECRET }}"
          "auth_url=${{ vars.AUTH_URL }}"
          "mongodb_uri=${{ secrets.MONGODB_URI }}"
          "mongodb_name=${{ vars.MONGODB_NAME }}"
          "next_public_base_url=${{ vars.NEXT_PUBLIC_BASE_URL }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'stockport-cu'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
        images: 'ghcr.io/${{ secrets.GHCR_USERNAME }}/shawsoft-io/un-capture-the-flag:latest'
      env:
        AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
        AUTH_STRAVA_ID: ${{ secrets.AUTH_STRAVA_ID }}
        AUTH_STRAVA_SECRET: ${{ secrets.AUTH_STRAVA_SECRET }}
        AUTH_URL: ${{ vars.AUTH_URL }}
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
        MONGODB_NAME: ${{ vars.MONGODB_NAME }}
        NEXT_PUBLIC_BASE_URL: ${{ vars.NEXT_PUBLIC_BASE_URL }}
